// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO-rEuIqOHCAVwLPg_Ysy3noj86bsDEgs',
    appId: '1:1061327501849:web:d54a650a7bd050fc968888',
    messagingSenderId: '1061327501849',
    projectId: 'ecommerceapp-eac38',
    authDomain: 'ecommerceapp-eac38.firebaseapp.com',
    storageBucket: 'ecommerceapp-eac38.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbbVFy7xPlJOT3f2jrFD3omQatyoztz90',
    appId: '1:1061327501849:android:814d3f1fd38d9d71968888',
    messagingSenderId: '1061327501849',
    projectId: 'ecommerceapp-eac38',
    storageBucket: 'ecommerceapp-eac38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkWVUNjcv3cHVIttwJtXKZ9tiY3iuvzZg',
    appId: '1:1061327501849:ios:35bfa829885e2ae6968888',
    messagingSenderId: '1061327501849',
    projectId: 'ecommerceapp-eac38',
    storageBucket: 'ecommerceapp-eac38.firebasestorage.app',
    androidClientId: '1061327501849-apqhjjhdfc0vfk27pe72viv4a3sa4bvo.apps.googleusercontent.com',
    iosClientId: '1061327501849-gfants3sl8ijiidsi6dj78ichk2sb1jk.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkWVUNjcv3cHVIttwJtXKZ9tiY3iuvzZg',
    appId: '1:1061327501849:ios:35bfa829885e2ae6968888',
    messagingSenderId: '1061327501849',
    projectId: 'ecommerceapp-eac38',
    storageBucket: 'ecommerceapp-eac38.firebasestorage.app',
    androidClientId: '1061327501849-apqhjjhdfc0vfk27pe72viv4a3sa4bvo.apps.googleusercontent.com',
    iosClientId: '1061327501849-gfants3sl8ijiidsi6dj78ichk2sb1jk.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO-rEuIqOHCAVwLPg_Ysy3noj86bsDEgs',
    appId: '1:1061327501849:web:c9da695c95fa0b62968888',
    messagingSenderId: '1061327501849',
    projectId: 'ecommerceapp-eac38',
    authDomain: 'ecommerceapp-eac38.firebaseapp.com',
    storageBucket: 'ecommerceapp-eac38.firebasestorage.app',
  );

}